# Generated by Django 5.2.4 on 2025-07-19 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('docs', models.TextField(max_length=900)),
                ('image', models.URLField(max_length=700)),
                ('location', models.CharField(max_length=700)),
                ('price', models.FloatField()),
                ('types', models.CharField(choices=[('ac', 'AC'), ('wifi', 'WIFI')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
