# Generated by Django 5.2.4 on 2025-08-03 08:07

import django.db.models.deletion
import multiselectfield.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('docs', models.TextField(max_length=900)),
                ('image', models.URLField(max_length=700)),
                ('location', models.CharField(max_length=700)),
                ('country', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.FloatField()),
                ('bed', models.IntegerField(blank=True, null=True)),
                ('bath', models.IntegerField(blank=True, null=True)),
                ('sqft', models.IntegerField(blank=True, null=True)),
                ('types', multiselectfield.db.fields.MultiSelectField(choices=[('ac', 'AC'), ('wifi', 'WIFI'), ('tv', 'TV'), ('geyser', 'Geyser')], max_length=100)),
                ('max_capacity', models.CharField(blank=True, choices=[('single', 'SINGLE'), ('duble', 'DUBLE'), ('triple', 'TRIPLE')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_booking', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
