# Generated by Django 5.2.4 on 2025-07-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='max_capacity',
            field=models.CharField(blank=True, choices=[('single', 'SINGLE'), ('duble', 'DUBLE'), ('triple', 'TRIPLE')], max_length=100, null=True),
        ),
    ]
