# Generated by Django 5.2.4 on 2025-08-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommodel',
            name='is_booking',
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='max_capacity',
            field=models.CharField(blank=True, choices=[('single', 'SINGLE'), ('double', 'DOUBLE'), ('triple', 'TRIPLE')], max_length=100, null=True),
        ),
    ]
