# Generated by Django 5.2.4 on 2025-08-03 11:17

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_roommodel_is_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ac', 'AC'), ('wifi', 'WIFI'), ('tv', 'TV'), ('geyser', 'Geyser'), ('breakfast', 'Breakfast')], max_length=100),
        ),
    ]
