# Generated by Django 5.2.4 on 2025-07-19 16:36

import multiselectfield.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_roommodel_max_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ac', 'AC'), ('wifi', 'WIFI'), ('tv', 'TV'), ('geyser', 'Geyser')], max_length=100),
        ),
    ]
