# Generated by Django 5.2.4 on 2025-07-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_roommodel_id_alter_roommodel_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
