# Generated by Django 5.2.4 on 2025-07-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_roommodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='district',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
