# Generated by Django 5.2.4 on 2025-07-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_roommodel_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='is_booking',
            field=models.BooleanField(default=True),
        ),
    ]
