# Generated by Django 5.2.4 on 2025-07-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_roommodel_is_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='is_booking',
            field=models.BooleanField(default=False),
        ),
    ]
