# Generated by Django 5.2.4 on 2025-07-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_alter_roommodel_is_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='bath',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='bed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='sqft',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
