# Generated by Django 5.2.4 on 2025-07-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_roommodel_bath_roommodel_bed_roommodel_sqft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommodel',
            old_name='district',
            new_name='country',
        ),
    ]
