# Generated by Django 5.2.4 on 2025-07-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_rename_district_roommodel_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roommodel',
            options={'ordering': ['-created_at']},
        ),
    ]
