# Generated by Django 5.2.4 on 2025-08-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmodel',
            options={'ordering': ['-created_at']},
        ),
    ]
