# Generated by Django 5.2.4 on 2025-07-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='booking_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
