# Generated by Django 5.1.3 on 2025-07-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
