# Generated by Django 5.2.4 on 2025-08-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activity',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
