# Generated by Django 5.1.3 on 2025-07-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0003_emailotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='ProfilePicture',
            new_name='profile',
        ),
    ]
