# Generated by Django 5.1.3 on 2025-07-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0004_rename_address_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('user', 'User'), ('hotel owner', 'Hotel Owner')], default='user', max_length=50, null=True),
        ),
    ]
