# Generated by Django 5.2.4 on 2025-08-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingmodel',
            options={'ordering': ['-created_at']},
        ),
    ]
