# Generated by Django 5.2.4 on 2025-08-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_bookingmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
