# Generated by Django 5.2.4 on 2025-08-24 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookingmodel_updated_at'),
        ('room', '0003_alter_roommodel_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingmodel', to='room.roommodel'),
        ),
    ]
